### ISSUE TITLE
Spotify Crashing

### ISSUE THREAD

**Issue by 5oulReaper14** [mrpond/BlockTheSpot#244]
When installing the new block the spot update my spotify just keeps crashing i reinstalled spotify and everything but it keeps saying spotify is not responding in that little box

**Comment by SirGryphin** [comment]
Same after latest update spotify crashes and closes after 30 seconds

**Comment by JustNightBG** [comment]
i have the same problem whit chrome_elf file but i dont want to use bat file either for safety

**Comment by malas0n** [comment]
same problem, only spotify doesnt actually open any window

**Comment by 5oulReaper14** [comment]
> same problem, only spotify doesnt actually open any window

same here guess we might have to wait??

**Comment by Ph1thak** [comment]
Same here

**Comment by Nuzair46** [comment]
Make sure to use the latest BlockTheSpot.bat .

Older bat file will have issues.

**Comment by Rafiuth** [comment]
This issue actually happens because the latest patch depends on the original `chrome_elf.dll` file being renamed to `chrome_elf_bak.dll`, the old script renames it to `chrome_elf.dll.bak`.

Reinstalling Spotify and updating `BlockTheSpot.bat` to the latest version should work as suggested by @Nuzair46.

**Comment by eduardodallmann** [comment]
Here work when I delete `chrome_elf_bak.dll` and `chrome_elf.dll.bak` files, reinstall Spotify, use last `BlockTheSpot.bat` and without removing placeholder.

**Comment by AmbassadorLaZer** [comment]
None of these work

**Comment by Nuzair46** [comment]
This issue will be marked as **SOLVED** as this is fixed by:

1. Uninstall Spotify.
2. Download **Latest (important)** BlockTheSpot.bat and run it.

The .bat file has been changed and the patch works in a new way. So please make sure everything is latest.

**Comment by Donny-Simmonds** [comment]
Unfortunately group policy rules block the bat file from running, just like they I try to run powershell.  From the mentions of the updated instructions it does not seem as though the manual method works at all? (copy/paste the files into the %appdata% folder from the zip file)

**Comment by MrFums** [comment]
Still not working for me after uninstall spotify and reinstalling the latest version of both spotify and the bat file

**Comment by solvz** [comment]
Still not working for me after uninstall spotify and reinstalling the latest version of both spotify and the bat file

**Comment by Donny-Simmonds** [comment]
@solvz @MrFums 

This is what worked for me:

1. Uninstall Spotify completely.
2. Download the latest version and install that.  Do not open or sign in yet.
3. Browse to (open in Explorer) the **%appdata%\spotify** folder.  (Windows key + R / use run command / file explorer etc)
4. Rename chrome_elf.dll to chrome_elf_bak.dll
5. Provided you've downloaded the bat file, run it now and follow the instructions
6. Run Spotify and it _SHOULD_ work

**Comment by gitgudscrubb** [comment]
@Donny-Simmonds method also works with the previous bat file by simply doing step 4 over a fresh non-windows store version installation. New bat file does not co-operate (has SSL/TSL issue from last time)

**Comment by zakblacki** [comment]
Not working only able to start with original chrome_elf.dll

**Comment by silverlays** [comment]
> Not working version 1.1.71.560.gc21c3367 I'm only able to start with original chrome_elf.dll

Same for me, trying every workaround given.
- Uninstall/Reinstall and using new .bat
- Don't apply placeholder patch

For information, when I launch Spotify, I can see it use my first core at 100% without doing anything else.

**Comment by zleng1129** [comment]
Spotify 1.1.72, whatever I do I still can't get this to work

**Comment by snakepit122** [comment]
when i put the chrome_elf app wont start anymore

**Comment by iDCoded** [comment]
> This issue will be marked as **SOLVED** as this is fixed by:
> 
>     1. Uninstall Spotify.
> 
>     2. Download **Latest (important)** BlockTheSpot.bat and run it.
> 
> 
> The .bat file has been changed and the patch works in a new way. So please make sure everything is latest.
> 
> Those who are still facing the issue, let me know if you use Spicetify.

Well, I use Spicetify and Spotify is not even launching for me.

**Comment by Neurotoxin001** [comment]
Not working on 1.1.81.604.gccacfc8c, after I put chrome_elf.dll Spotify stop launching.

**Comment by ArashGorge** [comment]
same here

**Comment by Neurotoxin001** [comment]
Idk what you're updating here https://github.com/mrpond/BlockTheSpot/commit/bdba3a39a260bda2c39c82887e0669603e49bfa5
But it's still crashing

**Comment by SmartManoj** [comment]
Just delete 'chrome_elf_bak.dll' in `%appdata%\spotify` folder if exists.
