### ISSUE TITLE
Spotify won't open after I made the latest version

### ISSUE THREAD

**Issue by elrond7** [mrpond/BlockTheSpot#254]
Make sure you have completed everything in the following checklist.

 - [x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [x] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [x] You uninstalled Spotify and just ran [BlockTheSpot.bat](https://raw.githack.com/mrpond/BlockTheSpot/master/BlockTheSpot.bat) and is still having issues.
 - [x] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [x] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [x] You enabled logging by editing config.ini `set log = 1`.

### Describe the bug
A clear and concise description of what the bug is, along with your OS [eg. Windows 10]:

Zip and attach the log file.

**Comment by Nuzair46** [comment]
fixed #244

**Comment by softyoda** [comment]
I have done all that, but spotify still won't open, and I have this error : 
![3007_Spotify_Spotify_03_11_2021_21h46(311x152)_Rb5K](https://user-images.githubusercontent.com/13988751/140190155-e8186d0c-90a7-4525-98a3-dcab95d56985.jpg)
 

The log only show : 

```
LOG | 03-Nov-2021 21:45:42 - GetModuleInformation OK!
LOG | 03-Nov-2021 21:45:42 - main process - patch success!

```
